In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('/Users/kchen/Downloads/ysg.csv')

In [35]:

for col in df.columns:
    print(col)
#del df['Unnamed: 0']
df.tail()

index
CommonName
teff_mc
teff_upper
teff_lower
logg_mc
logg_upper
logg_lower
radius_mc
radius_upper
radius_lower
teff_pm
lum_pm
halpha_emission
FYPS
source_id
lum_mc
lum_upper
lum_lower
ifmg_mc
ifmg_upper
ifmg_lower
binary

,index,CommonName,teff_mc,teff_upper,teff_lower,logg_mc,logg_upper,logg_lower,radius_mc,radius_upper,...,halpha_emission,FYPS,source_id,lum_mc,lum_upper,lum_lower,ifmg_mc,ifmg_upper,ifmg_lower,binary
34,34,HD 269110,3.714772,3.714858,3.714686,1.339994,1.345750,1.334422,354.100778,354.284606,...,True,False,4.652210e+18,4.912042,4.912193,4.911890,2.911542,2.917349,2.905538,1
35,35,HD 269787,4.070034,4.070037,4.070028,2.000034,2.000091,2.000008,122.604217,122.654862,...,True,True,4.660247e+18,5.411834,5.412192,5.411475,3.672538,3.672572,3.672477,2
36,36,HD 269807,3.875921,3.876043,3.873462,2.724490,2.729681,2.666055,147.284732,148.949062,...,False,False,4.660245e+18,4.794690,4.794852,4.794500,2.171776,2.219886,2.166660,1
37,37,HD 268971,4.070036,4.070037,4.070034,2.000021,2.000056,2.000005,70.605850,70.638926,...,False,False,4.655053e+18,4.932517,4.932924,4.932092,3.672565,3.672584,3.672530,2
38,38,HD 268865,3.749584,3.749651,3.749517,1.708236,1.713505,1.703012,200.607351,200.688168,...,False,False,4.661327e+18,4.557723,4.557858,4.557588,2.682544,2.687873,2.677160,1

In [ ]:
header = r"""\begin{deluxetable*}{clccccccc}
\tabletypesize{\scriptsize}
\tablecaption{Common names, coordinates, host galaxies, and \Gaia measurements of 6,484 putative massive stars. $r_{est}$ from \citet{bailerjones18} is given for Galactic stars. Listed values of $G$ and $G_{BP}-G_{RP}$ are uncorrected for extinction.\label{tab:sample}}
\tablehead{\colhead{Common Name} & \colhead{R.A. [deg]} & \colhead{Dec [deg]} & \colhead{Host Galaxy} & \colhead{$r_{est}$ [kpc]} & \colhead{$G$ [mag]} & \colhead{$A_G$ [mag]} & \colhead{$G_{BP}-G_{RP}$ [mag]}} 
\startdata
"""
j=0
for i,row in df.iterrows():
    if j == 39:
        break
    else:
        j+=1
    common_name = row['CommonName']
    # Teff
    teff_mc = row['teff_mc']
    teff_upper = row['teff_upper']
    teff_lower = row['teff_lower']
    teff_positive_error = teff_upper - teff_mc
    teff_negative_error = teff_mc - teff_lower
    teff_formatted = f"${teff_mc:.0f}\substack{{+{teff_positive_error:.3f} // -{teff_negative_error:.3f}}}$"

    # Logg
    logg_mc = row['logg_mc']
    logg_upper = row['logg_upper']
    logg_lower = row['logg_lower']
    logg_positive_error = logg_upper - logg_mc
    logg_negative_error = logg_mc - logg_lower
    logg_formatted = f"${logg_mc:.3f}\substack{{+{logg_positive_error:.3f} // -{logg_negative_error:.3f}}}$"

    # Radius
    radius_mc = row['radius_mc']
    radius_upper = row['radius_upper']
    radius_lower = row['radius_lower']
    radius_positive_error = radius_upper - radius_mc
    radius_negative_error = radius_mc - radius_lower
    radius_formatted = f"${radius_mc:.3f}\substack{{+{radius_positive_error:.3f} // -{radius_negative_error:.3f}}}$"
    
    # lum
    lum_mc = row['lum_mc']
    lum_upper = row['lum_upper']
    lum_lower = row['lum_lower']
    lum_positive_error = lum_upper - lum_mc
    lum_negative_error = lum_mc - lum_lower
    lum_formatted = f"${lum_mc:.3f}\substack{{+{lum_positive_error:.3f} // -{lum_negative_error:.3f}}}$"

    # ifmg
    ifmg_mc = row['teff_mc']
    ifmg_upper = row['teff_upper']
    ifmg_lower = row['teff_lower']
    ifmg_positive_error = teff_upper - teff_mc
    ifmg_negative_error = teff_mc - teff_lower
    ifmg_formatted = f"${teff_mc:.3f}\substack{{+{teff_positive_error:.3f} // -{teff_negative_error:.3f}}}$"
    
    index=row['index']
    teff_pm=row['teff_pm']
    lum_pm=row['lum_pm']
    halpha_emission=row['halpha_emission']
    fyps=row['FYPS']
    binary=row['binary']
    
    
    entry = list(map(str,[index,common_name,ra,dec,gal,rest,g,ag,bmr]))
    
    sep = ' & '
    
    header += sep.join(entry)
    header += ' \\\\ \n'
header.rstrip()
header.rstrip('\\')
header.rstrip()
header += r"""\enddata
\tablecomments{The first ten rows are shown to illustrate the content of the table. A complete machine-readable version will be made available online via Vizier.}
\end{deluxetable*}
â€‹
"""
with open("sample_table.txt", "w") as text_file:
        text_file.write(header)